services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password01!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
    networks:
      - genocs

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
 mssqlsystem:
   driver: local
 mssqluser:
   driver: local