global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway"]

  - job_name: "identity-service"
    static_configs:
      - targets: ["identity-service"]
 
  - job_name: "products-service"
    static_configs:
      - targets: ["products-service"]
 
  - job_name: "orders-service"
    static_configs:
      - targets: ["orders-service"]
 
  - job_name: "signalr-service"
    static_configs:
      - targets: ["signalr-service"]
